1. E igenvalues and Eigenvectors of an array

Explanation:
            NumPy has the numpy. linalg. eig() function to deduce the eigenvalues and normalized eigenvectors of a given square matrix. And since the returned eigenvectors are normalized, if you take the norm of the returned column vector, its norm will be 1.


Syntax:
        numpy.linalg.eig()
        np.linalg.eig(a)

In [1]:
#Code
import numpy as np

a = np.array([[3, 1], [2, 2]])
w, v = np.linalg.eig(a)

print(w)
print(v)


[4. 1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [2]:
print(np.allclose(np.dot(a,v[:,0]),np.dot(w[0],v[:,0])))

True


In [3]:
print(np.linalg.norm(v[:,0]))
print(np.linalg.norm(v[:,1]))

0.9999999999999999
0.9999999999999999


2. digitize
Explanation:
            With the help of np.digitize() method, we can get the indices of the bins to which the each value is belongs to an array by using np.digitize() method.
            
Syntax:
        np.digitize(Array, Bin, Right)
        Return : Return an array of indices of the bins.

In [4]:
#Code
import numpy as np 
  
a = np.array([1.2, 2.4, 3.6, 4.8]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0]) 
  
# using np.digitize() method 
gfg = np.digitize(a, bins) 
  
print(gfg) 

[1 2 3 4]


3. repeat()
Explanation:
            The numpy.repeat() function repeats elements of the array – arr.
Syntax:
       numpy.repeat(arr, repetitions, axis = None)
       
Parameters :

array       : [array_like]Input array. 
repetitions : No. of repetitions of each array elements along the given axis.
axis        : Axis along which we want to repeat values. By default, it returns 
           a flat output array.

Return :

An array with repetitions of array - arr elements as per repetitions, number of times 
we want to repeat arr  

In [5]:
#Code
import numpy as np 
  
#Working on 1D 
arr = np.arange(5) 
print("arr : \n", arr) 
  
repetitions = 2
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 2 times : \n", a) 
print("Shape : ", a.shape) 
  
repetitions = 3
a = np.repeat(arr, repetitions) 
print("\nRepeating arr 3 times : \n", a) 
# [0 0 0 ..., 4 4 4] means [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4] 
# since it was long output, so it uses [ ... ] 
print("Shape : ", a.shape) 

arr : 
 [0 1 2 3 4]

Repeating arr 2 times : 
 [0 0 1 1 2 2 3 3 4 4]
Shape :  (10,)

Repeating arr 3 times : 
 [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4]
Shape :  (15,)


4. squeeze()

Explanation:
               numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.
Syntax:
        numpy.squeeze(arr, axis=None )

Parameters :
arr : [array_like] Input array.
axis : [None or int or tuple of ints, optional] Selects a subset of the single-dimensional entries in the shape. If an axis is selected with shape entry greater than one, an error is raised.

Return :
squeezed [ndarray] The input array, but with all or a subset of the dimensions of length 1 removed. This is always a itself or a view into arr.

In [6]:
#Code
import numpy as np 
in_arr = np.arange(9).reshape(1, 3, 3)  
  
print ("Input array : ", in_arr)   
out_arr = np.squeeze(in_arr, axis = 0)  
  
print ("output array : ", out_arr)   
print("The shapes of Input and Output array : ")  
  
print(in_arr.shape, out_arr.shape) 

Input array :  [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
output array :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
The shapes of Input and Output array : 
(1, 3, 3) (3, 3)


5. linspace()

Explanation:
            The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.
            
Syntax:
        numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)
               
Parameters :

-> start  : [optional] start of interval range. By default start = 0
-> stop   : end of interval range
-> restep : If True, return (samples, step). By deflut restep = False
-> num    : [int, optional] No. of samples to generate
-> dtype  : type of output array



Return :

-> ndarray
-> step : [float, optional], if restep = True

In [7]:
#Code
import numpy as np 
  
# restep set to True 
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n") 
  
# To evaluate sin() in long range  
x = np.linspace(0, 2, 10) 
print("A\n", np.sin(x)) 

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


6. clip()

Explanation:
            numpy.clip() function is used to Clip (limit) the values in an array.

Given an interval, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1.


Syntax:
numpy.clip(a, a_min, a_max, out=None)

Parameters :
a : Array containing elements to clip.
a_min : Minimum value.
    –> If None, clipping is not performed on lower interval edge. Not more than one of a_min and a_max may be None.
a_max : Maximum value.
    –> If None, clipping is not performed on upper interval edge. Not more than one of a_min and a_max may be None.
    –> If a_min or a_max are array_like, then the three arrays will be broadcasted to match their shapes.
out : Results will be placed in this array. It may be the input array for in-place clipping. out must be of the right shape to hold the output. Its type is preserved.

Return : clipped_array

In [8]:
#Code
import numpy as np 
  
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", in_array) 
  
out_array = np.clip(in_array, a_min = 2, a_max = 6) 
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


7. extract()

Explanation:
            The numpy.extract() function returns elements of input_array if they satisfy some specified condition.
Syntax:
        numpy.extract(condition, array)
        
Parameters :

array     : Input array. User apply conditions on input_array elements
condition : [array_like]Condition on the basis of which user extract elements. 
      Applying condition on input_array, if we print condition, it will return an array
      filled with either True or False. Array elements are extracted from the Indices having 
      True value.
Returns :

Array elements that satisfy the condition.

In [9]:
import numpy as np 
  
array = np.arange(10).reshape(5, 2) 
print("Original array : \n", array) 
  
a = np.mod(array, 4) !=0
# This will show element status of satisfying condition 
print("\nArray Condition a : \n", a) 
  
# This will return elements that satisy condition "a" condition 
print("\nElements that satisfy condition a  : \n", np.extract(a, array)) 
  
  
  
b = array - 4 == 1
# This will show element status of satisfying condition 
print("\nArray Condition b : \n", b) 
  
# This will return elements that satisy condition "b" condition 
print("\nElements that satisfy condition b  : \n", np.extract(b, array)) 

Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Array Condition a : 
 [[False  True]
 [ True  True]
 [False  True]
 [ True  True]
 [False  True]]

Elements that satisfy condition a  : 
 [1 2 3 5 6 7 9]

Array Condition b : 
 [[False False]
 [False False]
 [False  True]
 [False False]
 [False False]]

Elements that satisfy condition b  : 
 [5]


8. argpartition()

Explanation:
            numpy.argpartition() function is used to create a indirect partitioned copy of input array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.It returns an array of indices of the same shape as arr, i.e arr[index_array] yields a partition of arr.
            
Syntax:
numpy.argpartition(arr, kth, axis=-1, kind=’introselect’, order=None)

Parameters :
arr : [array_like] Input array.
kth : [int or sequence of ints ] Element index to partition by.
axis : [int or None] Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.
kind : Selection algorithm. Default is ‘introselect’.
order : [str or list of str] When arr is an array with fields defined, this argument specifies which fields to compare first, second, etc.

Return : [index_array, ndarray] Array of indices that partition arr along the specified axis.

In [10]:
#Code
import numpy as geek 
  
# input array 
in_arr = geek.array([[ 2, 0,  1], [ 5, 4, 9] ]) 
print ("Input array : \n", in_arr)  
  
out_arr = geek.argpartition(in_arr, 1, axis = 1) 
print ("Output partitioned array indices :\n ", out_arr) 

Input array : 
 [[2 0 1]
 [5 4 9]]
Output partitioned array indices :
  [[1 2 0]
 [1 0 2]]



9. setdiff1d()

Explanation:
            numpy.setdiff1d() function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.
Syntax:
 numpy.setdiff1d(arr1, arr2, assume_unique = False)

Parameters :
arr1 : [array_like] Input array.
arr2 : [array_like] Input comparison array.
assume_unique : [bool] If True, the input arrays are both assumed to be unique, which can speed up the calculation. Default is False.

Return : [ndarray] 1D array of values in arr1 that are not in arr2. The result is sorted when assume_unique = False, but otherwise only sorted if the input is sorted.

In [11]:
import numpy as np  
   
arr1 = [5, 6, 2, 3, 4] 
arr2 = [1, 2, 3] 
   
gfg = np.setdiff1d(arr1, arr2) 
   
print (gfg)

[4 5 6]


10. itemsize

Explanation:
            numpy.ndarray.itemsize() function return the length of one array element in bytes.
Syntax:numpy.ndarray.itemsize(arr)

Parameters :
arr : [array_like] Input array.

Return : [int] The length of one array element in bytes

In [12]:
import numpy as py 
  
arr = py.array([1, 2, 3, 4], dtype = geek.float64) 
  
gfg = arr.itemsize 
  
print (gfg) 

8


11. hstack()

Explanation:
            numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

Syntax:
numpy.hstack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the second axis.

Return : [stacked ndarray] The stacked array of the input arrays.

In [13]:
#Code
import numpy as np 
  
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


12. vstack()

Explanation:
            numpy.vstack() function is used to stack the sequence of input arrays vertically to make a single array.
Syntax:
numpy.vstack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the first axis.

Return : [stacked ndarray] The stacked array of the input arrays.

In [14]:
#Code
  
import numpy as np 
  
# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays vertically 
out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


13. hsplit()

Explanation:
            numpy.hsplit() function split an array into multiple sub-arrays horizontally (column-wise). hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

Syntax : numpy.hsplit(arr, indices_or_sections)


Parameters :
arr : [ndarray] Array to be divided into sub-arrays.
indices_or_sections : [int or 1-D array] If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis.
If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split


Return : [ndarray] A list of sub-arrays.


In [15]:
#Code
import numpy as np 
  
arr = np.arange(16.0).reshape(4, 4) 
  
gfg = np.hsplit(arr, 2) 
  
print (gfg) 

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


14. vsplit()

Explanation:
            numpy.vsplit() function split an array into multiple sub-arrays vertically (row-wise). vsplit is equivalent to split with axis=0 (default), the array is always split along the first axis regardless of the array dimension.

Syntax : numpy.vsplit(arr, indices_or_sections)


Parameters :
arr : [ndarray] Array to be divided into sub-arrays.
indices_or_sections : [int or 1-D array] If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis.
If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split

Return : [ndarray] A list of sub-arrays.


In [16]:
#Code
import numpy as np 
  
arr = np.arange(9.0).reshape(3, 3) 
  
gfg = np.vsplit(arr, 1) 
  
print (gfg) 

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


15. View vs Shallow Copy

Explanation:
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


In [17]:
#Code
#Copy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Explanation:
Syntax:

In [18]:
#View
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


16. Deep Copy

Explanation:
            It returns a copy of the original array stored at a new location. The copy doesn’t share data or memory with the original array. The modifications are not reflected. The copy function is also known as deep copy.


In [19]:
#Code
import numpy as np
arr = np.array([20,30,50,70])
a= arr.copy()
#changing a value in original array
arr[0] = 100

print(arr)
print(a)

[100  30  50  70]
[20 30 50 70]


In [21]:
import copy 
  
# initializing list 1  
li1 = [1, 2, [3,5], 4] 
  
  
# using copy for shallow copy   
li2 = copy.copy(li1)  
  
# using deepcopy for deepcopy   
li3 = copy.deepcopy(li1) 
print(li2)
print()
print(li3)

[1, 2, [3, 5], 4]

[1, 2, [3, 5], 4]


17. copy()

Explanation:
        numpy.ndarray.copy() returns a copy of the array.

Syntax:
numpy.ndarray.copy(order=’C’)

Parameters:
order : Controls the memory layout of the copy. ‘C’ means C-order, ‘F’ means F-order, ‘A’ means ‘F’ if a is Fortran contiguous, ‘C’ otherwise. ‘K’ means match the layout of a as closely as possible.

In [22]:
#Code
import numpy as np 
  
  
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]], 
                                 order ='F') 
print("x is: \n", x) 
  
# copying x to y 
y = x.copy() 
print("y is :\n", y) 
print("\nx is copied to y") 

x is: 
 [[0 1 2 3]
 [4 5 6 7]]
y is :
 [[0 1 2 3]
 [4 5 6 7]]

x is copied to y


18. meshgrid()


Explanation:
            The numpy module of Python provides meshgrid() function for creating a rectangular grid with the help of the given 1-D arrays that represent the Matrix indexing or Cartesian indexing. MATLAB somewhat inspires the meshgrid() function. From the coordinate vectors, the meshgrid() function returns the coordinate matrices.

Syntax:
        numpy.meshgrid(*xi, **kwargs)  
Parameters
x1, x2,…, xn : array_like
This parameter defines the 1-dimensional array, which represents the coordinates of a grid.

indexing: {'xy', 'ij'}(optional)

This is an optional argument which defines the Cartesian 'xy'(by default) or matrix ('ij') indexing of output.

sparse: bool(optional)

This parameter is also optional. If we need a sparse grid for conserving memory, we have to set this parameter to True. By default, it is set to False.

copy: bool(optional)

The aim of this optional argument is that it returns a copy of the original array for conserving memory. By default, it is set to False.

If both sparse and copy parameters are set to False, then it will return non-contiguous arrays. In addition, more than one element of a broadcast array can refer to a single memory location. If we need to write into the arrays, then we have to make copies first.

Returns
X1, X2, …, Xn



In [25]:
#Code
import numpy as np  
na, nb = (5, 3)  
a = np.linspace(1, 2, na)  
b = np.linspace(1, 2, nb)  
xa, xb = np.meshgrid(a, b)  
print(xa)
print()

print(xb)

[[1.   1.25 1.5  1.75 2.  ]
 [1.   1.25 1.5  1.75 2.  ]
 [1.   1.25 1.5  1.75 2.  ]]

[[1.  1.  1.  1.  1. ]
 [1.5 1.5 1.5 1.5 1.5]
 [2.  2.  2.  2.  2. ]]


19. swapaxes()

Explanation:
            numpy.swapaxes() function interchange two axes of an array.

Syntax : numpy.swapaxes(arr, axis1, axis2)

Parameters :
arr : [array_like] input array.
axis1 : [int] First axis.
axis2 : [int] Second axis.
Return : [ndarray] In earlier NumPy versions, a view of arr is returned only if the order of the axes is changed, otherwise the input array is returned. For NumPy >= 1.10.0, if arr is an ndarray, then a view of arr is returned; otherwise a new array is created.


In [26]:
#Code
import numpy as np 
  
arr = np.array([[2, 4, 6]]) 
  
gfg = np.swapaxes(arr, 0, 1) 
  
print (gfg) 

[[2]
 [4]
 [6]]


20. column_stack()

Explanation:
            numpy.column_stack() function is used to stack 1-D arrays as columns into a 2-D array.It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack function.

Syntax : numpy.column_stack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same first dimension.

Return : [stacked 2-D array] The stacked 2-D array of the input arrays.


In [27]:
import numpy as geek 
  
# input array 
in_arr1 = geek.array(( 1, 2, 3 )) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array(( 4, 5, 6 )) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays  
out_arr = geek.column_stack((in_arr1, in_arr2)) 
print ("Output stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output stacked array:
  [[1 4]
 [2 5]
 [3 6]]
